-- SG Tutor Match: initial Supabase schema
-- Run this in the Supabase SQL Editor before using the live database.

create table if not exists public.parent_requests (
  id bigint generated by default as identity primary key,
  level text not null,
  subject text not null,
  lang text,
  postcode text,
  region text,
  address text,
  budget text,
  freq text,
  duration text,
  timeslot text,
  goal text,
  gender text,
  mode text,
  tutortype text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.tutor_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  scopes jsonb not null default '[]'::jsonb,
  level text,
  cred text,
  rate text,
  gender text,
  mode text,
  lang text,
  exp text,
  trial text,
  regions jsonb not null default '[]'::jsonb,
  timeslots jsonb not null default '[]'::jsonb,
  bio text,
  created_at timestamptz not null default now()
);

alter table public.parent_requests enable row level security;
alter table public.tutor_profiles enable row level security;

drop policy if exists "public insert parent requests" on public.parent_requests;
drop policy if exists "public read tutor profiles" on public.tutor_profiles;
drop policy if exists "public insert tutor profiles" on public.tutor_profiles;

-- Public demo phase. Tighten these policies after adding user accounts/auth.
create policy "public insert parent requests" on public.parent_requests for insert with check (true);
create policy "public read tutor profiles" on public.tutor_profiles for select using (true);
create policy "public insert tutor profiles" on public.tutor_profiles for insert with check (true);

create index if not exists parent_requests_created_at_idx on public.parent_requests(created_at desc);
create index if not exists tutor_profiles_created_at_idx on public.tutor_profiles(created_at desc);
