-- SG Tutor Match: platform matching + transaction data model
-- Existing demo tables are preserved. Run this file in Supabase SQL Editor.

create table if not exists public.parent_requests (
  id bigint generated by default as identity primary key,
  level text not null,
  subject text not null,
  lang text,
  postcode text,
  region text,
  address text,
  budget text,
  freq text,
  duration text,
  timeslot text,
  goal text,
  gender text,
  mode text,
  tutortype text,
  notes text,
  contact_name text,
  contact_phone text,
  contact_email text,
  contact_wechat text,
  request_status text not null default 'active' check (request_status in ('active','closed','removed')),
  removed_at timestamptz,
  removed_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.tutor_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  scopes jsonb not null default '[]'::jsonb,
  level text,
  cred text,
  rate text,
  gender text,
  mode text,
  lang text,
  exp text,
  trial text,
  regions jsonb not null default '[]'::jsonb,
  timeslots jsonb not null default '[]'::jsonb,
  bio text,
  whatsapp text,
  contact_email text,
  contact_phone text,
  tutor_status text not null default 'active' check (tutor_status in ('active','removed')),
  removed_at timestamptz,
  removed_reason text,
  created_at timestamptz not null default now()
);

alter table public.parent_requests add column if not exists contact_name text;
alter table public.parent_requests add column if not exists contact_phone text;
alter table public.parent_requests add column if not exists contact_email text;
alter table public.parent_requests add column if not exists contact_wechat text;
alter table public.parent_requests add column if not exists request_status text not null default 'active';
alter table public.parent_requests add column if not exists removed_at timestamptz;
alter table public.parent_requests add column if not exists removed_reason text;
alter table public.tutor_profiles add column if not exists whatsapp text;
alter table public.tutor_profiles add column if not exists contact_email text;
alter table public.tutor_profiles add column if not exists contact_phone text;
alter table public.tutor_profiles add column if not exists tutor_status text not null default 'active';
alter table public.tutor_profiles add column if not exists removed_at timestamptz;
alter table public.tutor_profiles add column if not exists removed_reason text;
update public.parent_requests set request_status='active' where request_status is null;
update public.tutor_profiles set tutor_status='active' where tutor_status is null;

drop view if exists public.parent_opportunities;
create view public.parent_opportunities as
select id, level, subject, lang, region, budget, freq, duration, timeslot, goal, gender, mode, tutortype, created_at
from public.parent_requests
where request_status = 'active';

drop view if exists public.tutor_public_profiles;
create view public.tutor_public_profiles as
select id, name, scopes, level, cred, rate, gender, mode, lang, exp, trial, regions, timeslots, bio, created_at
from public.tutor_profiles
where tutor_status = 'active';

create table if not exists public.match_interests (
  id bigint generated by default as identity primary key,
  parent_request_id bigint not null references public.parent_requests(id) on delete cascade,
  tutor_id bigint not null references public.tutor_profiles(id) on delete cascade,
  interested_by text not null check (interested_by in ('parent','tutor')),
  created_at timestamptz not null default now(),
  unique(parent_request_id, tutor_id, interested_by)
);

create table if not exists public.match_cases (
  id bigint generated by default as identity primary key,
  parent_request_id bigint not null references public.parent_requests(id) on delete cascade,
  tutor_id bigint not null references public.tutor_profiles(id) on delete cascade,
  status text not null default 'new' check (status in ('new','both_interested','contacting','trial','confirmed','not_concluded','cancelled')),
  parent_interested_at timestamptz,
  tutor_interested_at timestamptz,
  last_contacted_at timestamptz,
  confirmed_at timestamptz,
  confirmed_by uuid references auth.users(id),
  not_concluded_reason text,
  not_concluded_note text,
  hourly_rate numeric(10,2),
  lesson_duration_hours numeric(4,2),
  lessons_per_week numeric(4,2),
  first_lesson_date date,
  commission_amount numeric(10,2),
  commission_status text not null default 'pending' check (commission_status in ('pending','invoiced','paid','waived','cancelled')),
  platform_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(parent_request_id, tutor_id)
);

create table if not exists public.tutor_internal_scores (
  tutor_id bigint primary key references public.tutor_profiles(id) on delete cascade,
  level text not null default '普通' check (level in ('金牌','银牌','铜牌','普通','观察')),
  recommendations integer not null default 0,
  interests integer not null default 0,
  confirmed_deals integer not null default 0,
  not_concluded integer not null default 0,
  cancellations integer not null default 0,
  score numeric(8,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.parent_internal_scores (
  parent_request_id bigint primary key references public.parent_requests(id) on delete cascade,
  level text not null default '普通' check (level in ('黄质','银质','铜质','普通','观察')),
  requests integer not null default 0,
  interests integer not null default 0,
  confirmed_deals integer not null default 0,
  not_concluded integer not null default 0,
  cancellations integer not null default 0,
  score numeric(8,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists parent_requests_created_at_idx on public.parent_requests(created_at desc);
create index if not exists tutor_profiles_created_at_idx on public.tutor_profiles(created_at desc);
create index if not exists match_interests_parent_idx on public.match_interests(parent_request_id, created_at desc);
create index if not exists match_interests_tutor_idx on public.match_interests(tutor_id, created_at desc);
create index if not exists match_cases_status_idx on public.match_cases(status, created_at desc);
create index if not exists match_cases_tutor_idx on public.match_cases(tutor_id, created_at desc);

create or replace function public.set_match_case_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists match_cases_updated_at on public.match_cases;
create trigger match_cases_updated_at before update on public.match_cases
for each row execute function public.set_match_case_updated_at();

create or replace function public.validate_match_interest()
returns trigger language plpgsql security definer set search_path = public
as $
begin
  if not exists (
    select 1 from public.parent_requests
    where id = new.parent_request_id and request_status = 'active'
  ) then
    raise exception 'parent request is not active';
  end if;

  if not exists (
    select 1 from public.tutor_profiles
    where id = new.tutor_id and tutor_status = 'active'
  ) then
    raise exception 'tutor profile is not active';
  end if;

  return new;
end;
$;

drop trigger if exists validate_match_interest on public.match_interests;
create trigger validate_match_interest before insert on public.match_interests
for each row execute function public.validate_match_interest();

create or replace function public.register_match_interest()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.match_cases(parent_request_id, tutor_id, status, parent_interested_at, tutor_interested_at)
  values(
    new.parent_request_id,
    new.tutor_id,
    'new',
    case when new.interested_by = 'parent' then new.created_at else null end,
    case when new.interested_by = 'tutor' then new.created_at else null end
  )
  on conflict(parent_request_id, tutor_id) do update set
    parent_interested_at = coalesce(public.match_cases.parent_interested_at, excluded.parent_interested_at),
    tutor_interested_at = coalesce(public.match_cases.tutor_interested_at, excluded.tutor_interested_at),
    status = case
      when coalesce(public.match_cases.parent_interested_at, excluded.parent_interested_at) is not null
       and coalesce(public.match_cases.tutor_interested_at, excluded.tutor_interested_at) is not null
      then 'both_interested'
      else public.match_cases.status
    end;
  return new;
end;
$$;

drop trigger if exists match_interest_to_case on public.match_interests;
create trigger match_interest_to_case after insert on public.match_interests
for each row execute function public.register_match_interest();

alter table public.parent_requests enable row level security;
alter table public.tutor_profiles enable row level security;
alter table public.match_interests enable row level security;
alter table public.match_cases enable row level security;
alter table public.tutor_internal_scores enable row level security;
alter table public.parent_internal_scores enable row level security;
alter table public.platform_admins enable row level security;

drop policy if exists "public insert parent requests" on public.parent_requests;
create policy "public insert parent requests" on public.parent_requests for insert to anon, authenticated with check (true);

drop policy if exists "public read tutor profiles" on public.tutor_profiles;
create policy "public read tutor profiles" on public.tutor_profiles for select to anon, authenticated using (true);

drop policy if exists "public insert tutor profiles" on public.tutor_profiles;
create policy "public insert tutor profiles" on public.tutor_profiles for insert to anon, authenticated with check (true);

drop policy if exists "admins read tutor profiles" on public.tutor_profiles;
create policy "admins read tutor profiles" on public.tutor_profiles for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins update tutor profiles" on public.tutor_profiles;
create policy "admins update tutor profiles" on public.tutor_profiles for update to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true))
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "public insert match interests" on public.match_interests;
create policy "public insert match interests" on public.match_interests for insert to anon, authenticated with check (true);

revoke all on public.parent_requests from anon, authenticated;
grant insert on public.parent_requests to anon, authenticated;

revoke all on public.tutor_profiles from anon, authenticated;
grant insert on public.tutor_profiles to anon, authenticated;
grant select on public.tutor_profiles to authenticated;

revoke all on public.parent_opportunities from anon, authenticated;
grant select on public.parent_opportunities to anon, authenticated;
revoke all on public.tutor_public_profiles from anon, authenticated;
grant select on public.tutor_public_profiles to anon, authenticated;

revoke all on public.match_cases from anon, authenticated;
revoke all on public.tutor_internal_scores from anon, authenticated;
revoke all on public.parent_internal_scores from anon, authenticated;
revoke all on public.platform_admins from anon, authenticated;

grant select, update on public.match_cases to authenticated;
grant select on public.parent_requests to authenticated;
grant select on public.match_interests to authenticated;
grant select, insert, update on public.tutor_internal_scores to authenticated;
grant select, insert, update on public.parent_internal_scores to authenticated;
grant select on public.platform_admins to authenticated;

drop policy if exists "admins read platform admins" on public.platform_admins;
create policy "admins read platform admins" on public.platform_admins for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "admins read match cases" on public.match_cases;
create policy "admins read match cases" on public.match_cases for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins update match cases" on public.match_cases;
create policy "admins update match cases" on public.match_cases for update to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true))
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins read parent requests" on public.parent_requests;
create policy "admins read parent requests" on public.parent_requests for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins update parent requests" on public.parent_requests;
create policy "admins update parent requests" on public.parent_requests for update to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true))
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins read interests" on public.match_interests;
create policy "admins read interests" on public.match_interests for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins read tutor scores" on public.tutor_internal_scores;
create policy "admins read tutor scores" on public.tutor_internal_scores for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins update tutor scores" on public.tutor_internal_scores;
create policy "admins update tutor scores" on public.tutor_internal_scores for update to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true))
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins insert tutor scores" on public.tutor_internal_scores;
create policy "admins insert tutor scores" on public.tutor_internal_scores for insert to authenticated
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins read parent scores" on public.parent_internal_scores;
create policy "admins read parent scores" on public.parent_internal_scores for select to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins update parent scores" on public.parent_internal_scores;
create policy "admins update parent scores" on public.parent_internal_scores for update to authenticated
using (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true))
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

drop policy if exists "admins insert parent scores" on public.parent_internal_scores;
create policy "admins insert parent scores" on public.parent_internal_scores for insert to authenticated
with check (exists (select 1 from public.platform_admins a where a.user_id = (select auth.uid()) and a.active = true));

insert into public.tutor_internal_scores(tutor_id)
select id from public.tutor_profiles
on conflict(tutor_id) do nothing;
